### ISSUE TITLE
Add documentation about the development server

### ISSUE THREAD

**Issue by mafredri** [mafredri/openbttn#2]
OpenBttn contains a development server written in Go, it can be used for developing the web UI locally or for serving the OTA update for the SPWF01SA module.

* Installing: `go get github.com/mafredri/openbttn/cmd/openbttn`
* Usage: `openbttn -ip 192.168.0.123 -ota ./public/ota -public ./public/openbttn`
    * `-ip` assumes button is at IP `192.168.0.123`, used for redirecting some communication while developing the Web UI
    * `-ota` path to folder containing OTA image. Image can be downloaded from [here](http://www.st.com/content/st_com/en/products/embedded-software/wireless-connectivity-software/stsw-wifi001.html) (stsw-wifi001)
    * `-public` path to folder containing Web UI

Development server serves everything at `http://localhost:8774`.

**Comment by rjanja** [comment]
Doh, I just saw this. I thought I'd seen something similar in the past. I think this can be merged w/ the latest doc PR. I'll give it a go.
