### ISSUE TITLE
How to (re)set the management password ?

### ISSUE THREAD

**Issue by fvant** [mafredri/openbttn#7]
Flashed my bttn with your firmware, so far so good.
But how do I set/reset the password ?

**Comment by fvant** [comment]
got it, it is empty and \r\n  is enough

**Comment by mafredri** [comment]
Good to hear you got it sorted! In the future, you should be able to set it either from the recovery mode (hold button while booting) or via the socket server: `curl -w "\n" --data $'auth = PASSWORD\r\npassword = mynewpassword' $BTTNSOCK` (didn't try this, but should work, maybe \r\n at the end 😅).
